extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/dmulyalin
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/DMulyalin
markdown_extensions:
- admonition
- pymdownx.details
- attr_list
- md_in_html
- pymdownx.superfences
nav:
- Overview: index.md
- Contribute: contribute.md
- Writing docs: writing_docs.md
- API Reference: api_reference.md
- Templates:
  - Misc:
    - N2G:
      - cli_ip_data.a10: ttp_templates/misc.N2G.cli_ip_data.a10.md
      - cli_ip_data.cisco_ios: ttp_templates/misc.N2G.cli_ip_data.cisco_ios.md
      - cli_ip_data.cisco_nxos: ttp_templates/misc.N2G.cli_ip_data.cisco_nxos.md
      - cli_ip_data.cisco_xr: ttp_templates/misc.N2G.cli_ip_data.cisco_xr.md
      - cli_ip_data.fortinet: ttp_templates/misc.N2G.cli_ip_data.fortinet.md
      - cli_ip_data.huawei: ttp_templates/misc.N2G.cli_ip_data.huawei.md
      - cli_ip_data.readme: ttp_templates/misc.N2G.cli_ip_data.readme.md
      - cli_isis_data.cisco_xr: ttp_templates/misc.N2G.cli_isis_data.cisco_xr.md
      - cli_isis_data.juniper: ttp_templates/misc.N2G.cli_isis_data.juniper.md
      - cli_isis_data.readme: ttp_templates/misc.N2G.cli_isis_data.readme.md
      - cli_l2_data.cisco_ios: ttp_templates/misc.N2G.cli_l2_data.cisco_ios.md
      - cli_l2_data.cisco_nxos: ttp_templates/misc.N2G.cli_l2_data.cisco_nxos.md
      - cli_l2_data.cisco_xr: ttp_templates/misc.N2G.cli_l2_data.cisco_xr.md
      - cli_l2_data.huawei: ttp_templates/misc.N2G.cli_l2_data.huawei.md
      - cli_l2_data.juniper: ttp_templates/misc.N2G.cli_l2_data.juniper.md
      - cli_l2_data.readme: ttp_templates/misc.N2G.cli_l2_data.readme.md
      - cli_ospf_data.cisco_ios: ttp_templates/misc.N2G.cli_ospf_data.cisco_ios.md
      - cli_ospf_data.cisco_xr: ttp_templates/misc.N2G.cli_ospf_data.cisco_xr.md
      - cli_ospf_data.huawei: ttp_templates/misc.N2G.cli_ospf_data.huawei.md
      - cli_ospf_data.readme: ttp_templates/misc.N2G.cli_ospf_data.readme.md
    - Netmiko:
      - cisco.ios.arp: ttp_templates/misc.Netmiko.cisco.ios.arp.md
      - cisco.ios.cfg.bgp: ttp_templates/misc.Netmiko.cisco.ios.cfg.bgp.md
      - cisco.ios.cfg.interface: ttp_templates/misc.Netmiko.cisco.ios.cfg.interface.md
      - cisco.ios.cfg.ip: ttp_templates/misc.Netmiko.cisco.ios.cfg.ip.md
      - cisco.ios.cfg.nat.static: ttp_templates/misc.Netmiko.cisco.ios.cfg.nat.static.md
      - cisco.iosxr.arp: ttp_templates/misc.Netmiko.cisco.iosxr.arp.md
      - cisco.iosxr.cfg.interface: ttp_templates/misc.Netmiko.cisco.iosxr.cfg.interface.md
      - cisco.iosxr.cfg.ip: ttp_templates/misc.Netmiko.cisco.iosxr.cfg.ip.md
      - huawei.vrp.cfg.interface: ttp_templates/misc.Netmiko.huawei.vrp.cfg.interface.md
      - huawei.vrp.cfg.ip: ttp_templates/misc.Netmiko.huawei.vrp.cfg.ip.md
    - ttp_templates_tests:
      - cisco_ios_interfaces_cfg_per_ip: ttp_templates/misc.ttp_templates_tests.cisco_ios_interfaces_cfg_per_ip.md
      - netmiko_cisco_ios_interfaces: ttp_templates/misc.ttp_templates_tests.netmiko_cisco_ios_interfaces.md
  - Platform:
    - arista_eos_show_hostname: ttp_templates/platform.arista_eos_show_hostname.md
    - cisco_ios_show_ip_arp: ttp_templates/platform.cisco_ios_show_ip_arp.md
    - cisco_ios_show_ip_ospf_database_external: ttp_templates/platform.cisco_ios_show_ip_ospf_database_external.md
    - cisco_ios_show_ip_ospf_database_router: ttp_templates/platform.cisco_ios_show_ip_ospf_database_router.md
    - cisco_ios_show_ip_ospf_database_summary: ttp_templates/platform.cisco_ios_show_ip_ospf_database_summary.md
    - cisco_ios_show_running_configuration_pipe_section_bgp: ttp_templates/platform.cisco_ios_show_running_configuration_pipe_section_bgp.md
    - cisco_ios_show_running_config_pipe_include_source_static: ttp_templates/platform.cisco_ios_show_running_config_pipe_include_source_static.md
    - cisco_ios_show_running_config_pipe_section_interface: ttp_templates/platform.cisco_ios_show_running_config_pipe_section_interface.md
    - cisco_xr_show_arp_vrf_all: ttp_templates/platform.cisco_xr_show_arp_vrf_all.md
    - cisco_xr_show_isis_database_verbose: ttp_templates/platform.cisco_xr_show_isis_database_verbose.md
    - cisco_xr_show_ospf_database_external: ttp_templates/platform.cisco_xr_show_ospf_database_external.md
    - cisco_xr_show_ospf_database_router: ttp_templates/platform.cisco_xr_show_ospf_database_router.md
    - cisco_xr_show_ospf_database_summary: ttp_templates/platform.cisco_xr_show_ospf_database_summary.md
    - cisco_xr_show_running_config_interface: ttp_templates/platform.cisco_xr_show_running_config_interface.md
    - huawei_display_current_configuration_interface: ttp_templates/platform.huawei_display_current_configuration_interface.md
    - huawei_display_ospf_lsdb_router: ttp_templates/platform.huawei_display_ospf_lsdb_router.md
    - juniper_show_isis_database_verbose_pipe_no_more: ttp_templates/platform.juniper_show_isis_database_verbose_pipe_no_more.md
    - test_platform_show_run_pipe_sec_interface: ttp_templates/platform.test_platform_show_run_pipe_sec_interface.md
  - YANG:
    - ietf-interfaces_cisco_ios: ttp_templates/yang.ietf-interfaces_cisco_ios.md
    - openconfig-lldp_cisco_ios: ttp_templates/yang.openconfig-lldp_cisco_ios.md
    - openconfig-lldp_cisco_nxos: ttp_templates/yang.openconfig-lldp_cisco_nxos.md
    - openconfig-lldp_cisco_xr: ttp_templates/yang.openconfig-lldp_cisco_xr.md
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        rendering:
          docstring_section_style: list
          heading_level: 3
          merge_init_into_class: true
          show_object_full_path: true
          show_root_heading: true
          show_root_toc_entry: true
          show_signature_annotations: true
        selection:
          docstring_style: sphinx
repo_name: dmulyalin/ttp_templates
repo_url: https://github.com/dmulyalin/ttp_templates
site_author: Denis Mulyalin
site_description: TTP, parser, parsing, templates
site_name: TTP Templates Collection
site_url: https://ttp_templates.github.io/
theme:
  custom_dir: docs/overrides
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.top
  - toc.follow
  icon:
    repo: fontawesome/brands/github-alt
  name: material
  palette:
    accent: teal
    primary: blue
